meta_product_name: "Itrack"
meta_title: "Tell your Money where to go instead of wondering where it went."
meta_description: "Application that helps you manage monet better"
meta_image: "logo-itrack.png" # should exist in `app/assets/images/`
